// src/components/Navbar.vue
<template>
  <nav class="bg-white shadow-sm">
    <div class="container mx-auto px-4">
      <div class="flex justify-between items-center h-16">
        <div class="flex-shrink-0">
          <a href="/" class="text-2xl font-bold text-electric-500">Sole Street</a>
        </div>
        
        <div class="hidden md:block">
          <div class="ml-10 flex items-center space-x-4">
            <a href="#" class="text-gray-700 hover:text-electric-500 px-3 py-2 rounded-md text-sm font-medium">Men</a>
            <a href="#" class="text-gray-700 hover:text-electric-500 px-3 py-2 rounded-md text-sm font-medium">Women</a>
            <a href="#" class="text-gray-700 hover:text-electric-500 px-3 py-2 rounded-md text-sm font-medium">Collections</a>
            <a href="#" class="text-gray-700 hover:text-electric-500 px-3 py-2 rounded-md text-sm font-medium">About</a>
          </div>
        </div>
        
        <div class="flex items-center space-x-4">
          <button class="text-gray-700 hover:text-electric-500">
            <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
          </button>
          <button class="text-gray-700 hover:text-electric-500">
            <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
            </svg>
          </button>
          <button class="text-gray-700 hover:text-electric-500">
            <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
          </button>
          
          <button class="md:hidden text-gray-700 hover:text-electric-500" @click="isMenuOpen = !isMenuOpen">
            <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path v-if="!isMenuOpen" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
              <path v-else stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div>
    
    <!-- Mobile menu -->
    <div v-if="isMenuOpen" class="md:hidden">
      <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
        <a href="#" class="text-gray-700 hover:text-electric-500 block px-3 py-2 rounded-md text-base font-medium">Men</a>
        <a href="#" class="text-gray-700 hover:text-electric-500 block px-3 py-2 rounded-md text-base font-medium">Women</a>
        <a href="#" class="text-gray-700 hover:text-electric-500 block px-3 py-2 rounded-md text-base font-medium">Collections</a>
        <a href="#" class="text-gray-700 hover:text-electric-500 block px-3 py-2 rounded-md text-base font-medium">About</a>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const isMenuOpen = ref(false)
</script>

// src/components/Navbar.tsx

import { useState, useEffect } from "react";
import { Menu, ShoppingBag, X, Search, User } from "lucide-react";
import { Button } from "@/components/ui/button";

const Navbar = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isScrolled, setIsScrolled] = useState(false);
  
  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 10);
    };
    
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);
  
  return (
    <header className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${isScrolled ? "bg-white shadow-md py-2" : "bg-transparent py-4"}`}>
      <div className="container mx-auto px-4">
        <div className="flex items-center justify-between">
          {/* Logo */}
          <a href="/" className="flex items-center">
            <span className={`text-2xl font-montserrat font-black tracking-tight ${isScrolled ? "text-black" : "text-white"}`}>
              SOLE<span className="text-electric-500">STREET</span>
            </span>
          </a>
          
          {/* Desktop Navigation */}
          <nav className="hidden md:flex items-center space-x-8">
            <a href="#new-arrivals" className={`font-medium hover:text-electric-500 transition-colors ${isScrolled ? "text-gray-700" : "text-white"}`}>
              New Arrivals
            </a>
            <a href="#best-sellers" className={`font-medium hover:text-electric-500 transition-colors ${isScrolled ? "text-gray-700" : "text-white"}`}>
              Best Sellers
            </a>
            <a href="#limited-drops" className={`font-medium hover:text-electric-500 transition-colors ${isScrolled ? "text-gray-700" : "text-white"}`}>
              Limited Drops
            </a>
            <a href="#collections" className={`font-medium hover:text-electric-500 transition-colors ${isScrolled ? "text-gray-700" : "text-white"}`}>
              Collections
            </a>
          </nav>
          
          {/* Desktop Actions */}
          <div className="hidden md:flex items-center space-x-4">
            <button className={`p-1 rounded-full hover:bg-black/10 transition-colors ${isScrolled ? "text-gray-700" : "text-white"}`}>
              <Search size={20} />
            </button>
            <button className={`p-1 rounded-full hover:bg-black/10 transition-colors ${isScrolled ? "text-gray-700" : "text-white"}`}>
              <User size={20} />
            </button>
            <button className={`p-1 rounded-full hover:bg-black/10 transition-colors relative ${isScrolled ? "text-gray-700" : "text-white"}`}>
              <ShoppingBag size={20} />
              <span className="absolute -top-1 -right-1 bg-electric-500 text-white text-xs font-bold rounded-full w-4 h-4 flex items-center justify-center">
                2
              </span>
            </button>
          </div>
          
          {/* Mobile Menu Button */}
          <div className="flex items-center md:hidden space-x-4">
            <button className={`p-1 rounded-full hover:bg-black/10 transition-colors relative ${isScrolled ? "text-gray-700" : "text-white"}`}>
              <ShoppingBag size={20} />
              <span className="absolute -top-1 -right-1 bg-electric-500 text-white text-xs font-bold rounded-full w-4 h-4 flex items-center justify-center">
                2
              </span>
            </button>
            <button 
              className={`p-2 rounded-md ${isScrolled ? "text-gray-700" : "text-white"}`} 
              onClick={() => setIsMenuOpen(!isMenuOpen)}
            >
              <Menu size={24} />
            </button>
          </div>
        </div>
      </div>
      
      {/* Mobile Menu */}
      <div className={`fixed inset-0 bg-black z-50 transition-transform duration-300 ${isMenuOpen ? "translate-x-0" : "translate-x-full"}`}>
        <div className="flex justify-end p-4">
          <button className="text-white p-2" onClick={() => setIsMenuOpen(false)}>
            <X size={24} />
          </button>
        </div>
        <div className="flex flex-col items-center justify-center h-full space-y-8">
          <a href="#new-arrivals" className="text-white text-2xl font-montserrat" onClick={() => setIsMenuOpen(false)}>
            New Arrivals
          </a>
          <a href="#best-sellers" className="text-white text-2xl font-montserrat" onClick={() => setIsMenuOpen(false)}>
            Best Sellers
          </a>
          <a href="#limited-drops" className="text-white text-2xl font-montserrat" onClick={() => setIsMenuOpen(false)}>
            Limited Drops
          </a>
          <a href="#collections" className="text-white text-2xl font-montserrat" onClick={() => setIsMenuOpen(false)}>
            Collections
          </a>
          <div className="flex space-x-6 mt-8">
            <button className="text-white">
              <Search size={24} />
            </button>
            <button className="text-white">
              <User size={24} />
            </button>
          </div>
        </div>
      </div>
    </header>
  );
};

export default Navbar;
