// src/components/Newsletter.vue
<template>
  <section class="py-16 px-4 bg-gray-900">
    <div class="container mx-auto max-w-2xl text-center">
      <h2 class="text-3xl text-white md:text-4xl font-bold mb-4">Stay Updated</h2>
      <p class="text-gray-600 mb-8">Subscribe to our newsletter for exclusive offers and updates.</p>
      
      <form @submit.prevent="handleSubmit" class="flex flex-col sm:flex-row gap-4">
        <input
          type="email"
          v-model="email"
          placeholder="Enter your email"
          class="flex-1 px-4 py-3 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-electric-500"
          required
        />
        <button
          type="submit"
          class="px-6 py-3 bg-electric-500 text-white font-medium rounded-lg hover:bg-electric-600 transition-colors"
        >
          Subscribe
        </button>
      </form>
      
      <p v-if="isSubscribed" class="mt-4 text-green-600">
        Thank you for subscribing!
      </p>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const email = ref('')
const isSubscribed = ref(false)

const handleSubmit = () => {
  console.log('Subscribed with email:', email.value)
  isSubscribed.value = true
  email.value = ''
}
</script>

// src/components/Newsletter.tsx

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/components/ui/use-toast';

const Newsletter = () => {
  const [email, setEmail] = useState('');
  const [focused, setFocused] = useState(false);
  const { toast } = useToast();
  
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (email) {
      toast({
        title: "Success!",
        description: "You've been subscribed to our newsletter.",
      });
      setEmail('');
    }
  };
  
  return (
    <section className="bg-black text-white py-20 px-4">
      <div className="container mx-auto">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">Stay in the Loop</h2>
          <p className="text-lg text-gray-300 mb-8">
            Sign up for our newsletter to receive exclusive offers, early access to drops, and style inspiration.
          </p>
          
          <form onSubmit={handleSubmit} className="flex flex-col md:flex-row gap-4 max-w-md mx-auto">
            <div className="relative flex-grow">
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                onFocus={() => setFocused(true)}
                onBlur={() => setFocused(false)}
                className="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-md text-white focus:outline-none focus:border-electric-500 transition-colors"
                required
              />
              <label 
                className={`absolute left-4 transition-all duration-200 pointer-events-none ${
                  focused || email ? 'text-xs text-electric-400 -top-2.5 bg-black px-1' : 'text-gray-400 top-3'
                }`}
              >
                Your Email
              </label>
            </div>
            <Button 
              type="submit"
              className="bg-electric-500 hover:bg-electric-600 text-white py-3 px-6 rounded-md"
            >
              Subscribe
            </Button>
          </form>
        </div>
      </div>
    </section>
  );
};

export default Newsletter;
